services:
  - type: web
    name: your-app-name
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RUBY_VERSION
        value: 3.2.2
