default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  port : 3306
  password:
  host: localhost

development:
  <<: *default
  database: sql_chat_development

test:
  <<: *default
  database: sql_chat_test

production:
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5

