default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sql_chat_development
  username: sql_chatbot_production_user
  password: to0SEdK6gMxoZnIEusytYRmODOUwDWV7
  host: dpg-d0r0m6e3jp1c739cc7n0-a
  port: 5432

test:
  <<: *default
  database: sql_chat_test
  username: sql_chatbot_production_user
  password: to0SEdK6gMxoZnIEusytYRmODOUwDWV7
  host: dpg-d0r0m6e3jp1c739cc7n0-a
  port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] || 'postgresql://sql_chatbot_production_user:to0SEdK6gMxoZnIEusytYRmODOUwDWV7@dpg-d0r0m6e3jp1c739cc7n0-a/sql_chatbot_production' %>
