default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock
  port: 3306

development:
  <<: *default
  database: sql_chatbot_development

test:
  <<: *default
  database: sql_chatbot_test

production:
  <<: *default
  database: sql_chatbot_production
  username: <%= ENV['MYSQL_USER'] || 'root' %>
  password: <%= ENV['MYSQL_PASSWORD'] || '' %>
  socket: <%= ENV['MYSQL_SOCKET'] || '/var/run/mysqld/mysqld.sock' %>
