default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: 2211
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: sql_chat_development

test:
  <<: *default
  database: sql_chat_test

production:
  <<: *default
  database: sql_chat_production
  # username: <%= ENV['MYSQL_USERNAME'] %>
  # password: <%= ENV['MYSQL_PASSWORD'] %>
